CREATE TABLE type_eclipse(id_eclipse INT PRIMARY KEY,nom VARCHAR(10),type VARCHAR(10),description TEXT,id_phenomene INT);
INSERT INTO type_eclipse (id_eclipse,nom,type,description,id_phenomene) VALUES 
(1,'solaire','T-','Éclipse solaire totale, phase initiale — Le début de la totalité.',4),
(2,'solaire','P','Éclipse solaire partielle — Une partie seulement du Soleil est occultée par la Lune.',4),
(3,'solaire','T+','Éclipse solaire totale, phase finale — Fin de la totalité, retour à partielle.',4),
(4,'solaire','N','Éclipse solaire annulaire (nœud) — La Lune couvre le Soleil en laissant un anneau lumineux.',4),
(5,'solaire','T','Éclipse solaire totale — Le Soleil est complètement occulté par la Lune.',4),
(6,'solaire','Nb','Éclipse solaire au nœud descendant — L’éclipse se produit lorsque la Lune traverse le nœud descendant.',4),
(7,'solaire','Ne','Éclipse solaire au nœud ascendant — L’éclipse se produit lorsque la Lune traverse le nœud ascendant.',4),
(8,'solaire','Nx','Éclipse solaire proche d’un nœud — Eclipse près du nœud, type spécifique non précisé.',4),
(9,'lunaire','T','Éclipse lunaire totale — La Lune passe entièrement dans l’ombre de la Terre (umbra).',3),
(10,'lunaire','A','Éclipse lunaire annulaire / pénombrale — Ombre partielle sur la Lune.',3),
(11,'lunaire','P','Éclipse lunaire partielle — Une partie seulement de la Lune entre dans l’ombre de la Terre.',3),
(12,'lunaire','Pb','Éclipse lunaire pénombrale, phase initiale — La Lune commence à entrer dans la pénombre.',3),
(13,'lunaire','H','Éclipse lunaire partielle dans l’ombre (mi-ombre) — Une portion significative dans l’ombre, mais pas totale.',3),
(14,'lunaire','Pe','Éclipse lunaire pénombrale, phase finale — La Lune sort progressivement de la pénombre.',3),
(15,'lunaire','A+','Éclipse lunaire quasi-totale — Presque toute la Lune est couverte par l’ombre.',3),
(16,'lunaire','H3','Éclipse lunaire partielle avec 3/4 de couverture — La Lune est majoritairement dans l’ombre terrestre.',3),
(17,'lunaire','Hm','Éclipse lunaire partielle, phase médiane — La Lune est partiellement occultée à mi-temps.',3),
(18,'lunaire','An','Éclipse lunaire annulaire / pénombrale au nœud — Lune proche du nœud, pas de totalité.',3),
(19,'lunaire','H2','Éclipse lunaire partielle, moitié de couverture — La moitié de la Lune dans l’ombre.',3),
(20,'lunaire','Tm','Éclipse lunaire totale, phase médiane — La Lune entièrement dans l’ombre au milieu de l’éclipse.',3),
(21,'lunaire','Am','Éclipse lunaire quasi-totale — La couverture de la Lune est presque complète.',3),
(22,'lunaire','T+','Éclipse lunaire totale, phase finale — La Lune sort de l’ombre (fin de la totalité).',3),
(23,'lunaire','A-','Éclipse lunaire quasi-totale, phase initiale — La Lune commence à être complètement couverte.',3),
(24,'lunaire','T-','Éclipse lunaire totale, phase initiale — La Lune entre dans l’ombre (début de la totalité).',3);